apiVersion: v1
kind: Service
metadata:
  name: {{ include "haliphron.fullname" . }}
  labels: {{- include "haliphron.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "haliphron.selectorLabels" . | nindent 4 }}
  ports:
    {{- if (include "haliphron.servesAPI" .) }}
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
    {{- end }}
    {{- if (include "haliphron.servesMCP" .) }}
    - name: mcp
      port: {{ .Values.service.ports.mcp }}
      targetPort: mcp
      protocol: TCP
    {{- end }}
    {{- if (include "haliphron.servesCluster" .) }}
    - name: cluster
      port: {{ .Values.service.ports.cluster }}
      targetPort: cluster
      protocol: TCP
    {{- end }}
    - name: health
      port: {{ .Values.service.ports.health }}
      targetPort: health
      protocol: TCP
