package app

import (
	"context"
	"strings"
	"time"

	runv1 "github.com/automagicops/haliphron/api/run/v1"
	"github.com/automagicops/haliphron/backend/artifacts"
)

// Retention for the artifact store.
//
// This is one of the three real costs of relay mode, stated in section 9.2 and
// paid here: no lifecycle rules for free. An object store is told "expire this
// prefix after thirty days" once and does the work itself; a volume has to be
// walked. Object-store mode gets ILM or S3 lifecycle rules generated by the
// chart and never reaches this loop.
//
// Three ages rather than one, because the three kinds of object have different
// value. A log is worth thirty days — long enough to diagnose last month's
// failure, short enough that logs do not become the volume. A result is worth
// half a year, because it is the thing somebody paid for. Artifacts sit between
// them.

// Retention is how long each kind of object is kept.
type Retention struct {
	Logs    time.Duration
	Results time.Duration
	Other   time.Duration
}

// ageFor is which of the three ages applies to a key.
//
// It matches on the layout rather than on a stored classification, which is
// only possible because the layout is fixed and identical in both modes. The
// alternative — a table of objects with their kinds — is the artifacts index
// the store contract deliberately does not have: an index that has to be kept
// in agreement with a filesystem is a source of divergence rather than answers.
func (r Retention) ageFor(key string) time.Duration {
	name := key
	if idx := strings.Index(key, "/"); idx >= 0 {
		// Past runs/{id}/ to the part of the key that says what this is.
		if rest := strings.SplitN(key, "/", 3); len(rest) == 3 {
			name = rest[2]
		}
	}
	switch {
	case strings.HasPrefix(name, "logs/"):
		return r.Logs
	case name == runv1.StorageKeyResult || name == runv1.StorageKeyOutput ||
		name == runv1.StorageKeyCompletion:
		return r.Results
	default:
		return r.Other
	}
}

// ReapArtifacts deletes what has outlived its retention.
//
// It runs only in relay mode. Calling it against an object store would be
// correct and pointless: the lifecycle rules the chart generated are already
// doing it, more cheaply and without a LIST of every object in the bucket on
// every interval.
//
// A zero age means keep forever, which is what an installation that has not
// thought about retention should get. Deleting a customer's results because a
// configuration value defaulted is not a failure mode worth having.
func (s *Service) ReapArtifacts(ctx context.Context, interval time.Duration, keep Retention) {
	if s.artifacts.Mode() != runv1.ArtifactModeRelay {
		return
	}
	if interval <= 0 {
		interval = time.Hour
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			deleted, err := s.reapOnce(ctx, keep)
			if err != nil && !ctxDone(ctx) {
				s.log.Error("reaping artifacts failed", "error", err)
				continue
			}
			if deleted > 0 {
				s.log.Info("expired artifacts deleted", "objects", deleted)
			}
		}
	}
}

func (s *Service) reapOnce(ctx context.Context, keep Retention) (int, error) {
	objects, err := s.artifacts.List(ctx, "runs/")
	if err != nil {
		return 0, err
	}
	now := s.now()

	var deleted int
	for _, obj := range objects {
		age := keep.ageFor(obj.Key)
		if age <= 0 || now.Sub(obj.LastModified) < age {
			continue
		}
		if err := s.artifacts.Delete(ctx, obj.Key); err != nil {
			// One object that will not delete is not a reason to stop: the
			// rest of the sweep is still worth doing, and a permission problem
			// on one key would otherwise stop retention for the whole volume.
			s.log.Warn("could not delete an expired artifact", "key", obj.Key, "error", err)
			continue
		}
		deleted++
		if ctxDone(ctx) {
			break
		}
	}
	return deleted, nil
}

// artifactStoreRef is Ref over this service's store, for the callers that build
// a result_ref without reaching for the port.
func (s *Service) artifactStoreRef(key string) string { return artifacts.Ref(s.artifacts, key) }
