package run

import (
	"time"

	clusterv1 "github.com/automagicops/haliphron/api/cluster/v1"
	runv1 "github.com/automagicops/haliphron/api/run/v1"
)

// Section 5 of the Cluster API contract, as a function.
//
// At-least-once delivery with retries and backoff means reports arrive
// reordered, and the rule that keeps a run's state from being decided by
// network timing is that ordering is by (attempt, phaseRank) and never by
// time. Cluster clocks are not synchronised; ObservedAt in a report is for
// diagnostics and is not read here.
//
// The function is pure and the caller does the writing, which is what lets the
// three paths that apply a report — /ingest/status, the runs[] of a heartbeat,
// and the completion envelope's epoch check — share one reading of the rules
// while holding one row lock each.

// State is the run as lock_run.sql returns it: everything the decision needs
// and nothing else.
type State struct {
	RunID     runv1.ULID
	ClusterID runv1.ULID
	Epoch     int64
	Attempt   int32
	Status    string

	// Phase and Rank are the observation half of the row. Rank is generated by
	// the database from Phase, so the two cannot disagree; it is carried here
	// rather than recomputed so that a phase written by a newer build is
	// compared at the rank the database gave it.
	Phase runv1.Phase
	Rank  int

	FailureClass         runv1.FailureClass
	CancelRequestedAt    *time.Time
	CompletionReceivedAt *time.Time
	AckDeadline          *time.Time
	LeaseDeadline        *time.Time
}

// Terminal reports whether the run has already ended as far as the store is
// concerned.
func (s State) Terminal() bool { return s.Phase.IsTerminal() }

// Verdict is what to do with an observation.
type Verdict int

const (
	// Advance means the observation moves the run forward and is written in
	// full: phase, status, reason, class and the timestamps it implies.
	Advance Verdict = iota

	// Repeat means the observation says what the store already holds. It is
	// accepted, and it writes exactly one thing: the status, so that a run
	// marked Unknown while its cluster was unreachable comes back to Running
	// on the first report that arrives after the link returns. That recovery
	// is the entire reason Unknown lives in status and not in observed_phase.
	Repeat

	// Reject means the observation is not applied. The code and the action say
	// why and what the controller should do about it.
	Reject
)

// Decision is the verdict plus what the caller owes the controller.
type Decision struct {
	Verdict Verdict

	// NewAttempt means the controller started another attempt of its own. The
	// phase rank resets — otherwise a Pending from attempt 2 loses to the
	// Succeeded of attempt 1 — and a row is written to run_attempts, which is
	// the accounting unit.
	NewAttempt bool

	Code   clusterv1.ProblemCode
	Action clusterv1.Action

	// Audit is set when something was discarded and the silence would be the
	// problem: a second, different ending for the same attempt.
	Audit bool
}

// Accepted reports whether the controller should regard the observation as
// delivered.
func (d Decision) Accepted() bool { return d.Verdict != Reject }

// Apply evaluates one observation against the current row.
//
// clusterID is the authenticated caller. It is checked here rather than in the
// handler because "this run belongs to somebody else now" and "this epoch is
// stale" are the same class of failure — a controller acting on work it no
// longer owns — and they are answered the same way: abandon.
func Apply(state State, obs clusterv1.RunObservation, clusterID runv1.ULID) Decision {
	switch {
	case obs.Epoch < state.Epoch:
		// A zombie. It was disconnected, its work was reassigned, and it has
		// come back with news about a run that is no longer its own.
		return Decision{Verdict: Reject, Code: clusterv1.CodeEpochMismatch, Action: clusterv1.ActionAbandon}

	case obs.Epoch > state.Epoch:
		// The backend never issued this epoch. Not a race — a defect, and no
		// retry improves it.
		return Decision{Verdict: Reject, Code: clusterv1.CodeInvalidRequest, Action: clusterv1.ActionFatal}

	case state.ClusterID != "" && state.ClusterID != clusterID:
		return Decision{Verdict: Reject, Code: clusterv1.CodeRunLeasedByAnotherCluster, Action: clusterv1.ActionAbandon}

	case obs.Attempt < state.Attempt:
		return Decision{Verdict: Reject, Code: clusterv1.CodeAttemptRegression, Action: clusterv1.ActionAbandon}
	}

	rank := obs.Phase.Rank()
	if rank == 0 {
		// A phase this build has never heard of. Ignoring it is the
		// compatibility rule from section 11: a newer controller must not be
		// able to move a run into a state this backend cannot reason about,
		// and must not be crashed for trying either.
		return Decision{Verdict: Reject, Code: clusterv1.CodeInvalidRequest, Action: clusterv1.ActionFatal}
	}

	if obs.Attempt > state.Attempt {
		return Decision{Verdict: Advance, NewAttempt: true}
	}

	switch {
	case rank > state.Rank:
		return Decision{Verdict: Advance}

	case rank == state.Rank && obs.Phase == state.Phase:
		// The same observation delivered twice, which at-least-once delivery
		// guarantees will happen. It is also the message that clears Unknown.
		return Decision{Verdict: Repeat}

	case rank == state.Rank && state.Terminal():
		// Two different endings for one attempt. The first stands — reversing
		// a terminal state on a late message is how a succeeded run becomes
		// failed in the UI while its PR sits open — and the disagreement goes
		// to the audit log rather than nowhere.
		return Decision{
			Verdict: Reject, Code: clusterv1.CodeRunTerminal,
			Action: clusterv1.ActionAbandon, Audit: true,
		}

	default:
		// Almost always reordering within a batch rather than lost ownership,
		// so: retry. The next heartbeat carries the current state and settles
		// it. Abandon here would throw away a live run over a swapped pair of
		// packets.
		return Decision{Verdict: Reject, Code: clusterv1.CodePhaseRegression, Action: clusterv1.ActionRetry}
	}
}

// StatusFor is the backend status implied by an observed phase, with the one
// case the mapping table in section 5 does not cover: a terminal phase whose
// completion report has not arrived.
//
// That case is not a failure. The pod writes its result to storage before it
// calls back (ADR 15), so the contents exist and the backend owes itself a
// read. It is reported to the controller as CompletedWithoutResult and stored
// as the terminal status it is — the run_status domain has no value for it,
// deliberately: "the result has not been collected yet" is the absence of
// completion_received_at, not a state of the run.
func StatusFor(phase runv1.Phase, completionReceived bool) string {
	status := clusterv1.StatusForPhase(phase)
	if phase.IsTerminal() && !completionReceived {
		return clusterv1.StatusCompletedWithoutResult
	}
	return status
}

// StoredStatus is what goes into the status column for an observed phase.
// Unlike StatusFor it never returns CompletedWithoutResult, which the schema
// cannot hold.
func StoredStatus(phase runv1.Phase) string { return clusterv1.StatusForPhase(phase) }
