package artifacts

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"hash"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"

	clusterv1 "github.com/automagicops/haliphron/api/cluster/v1"
	runv1 "github.com/automagicops/haliphron/api/run/v1"
)

// Disk is the default ArtifactStore: a directory, normally a PVC mounted on the
// backend.
//
// It is what makes object storage optional. The bytes arrive relayed from a
// controller rather than pushed by a pod, which puts the backend in the artifact
// data path — a real cost, accepted deliberately and mitigated by the per-run
// byte cap and by the log chunking that already existed. What it buys is an
// installation that runs its first agent without standing up MinIO.
//
// Two properties of the volume are worth stating because they shape deployment
// rather than code. A PVC is ReadWriteOnce on most storage classes, so the
// replica serving artifact writes must be singular unless the chart is given an
// RWX class — the honest statement is that relay mode with an RWO volume pins
// the *artifact writer* to one replica, not the whole control plane, since the
// rest of the backend scales freely on SKIP LOCKED. And there are no lifecycle
// rules for free: retention is the backend's own reaper walking this tree by
// prefix age, where object-store mode would have ILM or S3 lifecycle rules
// generated by the chart.
type Disk struct {
	root string
	// perm is the mode new files get. Directories get perm|0111.
	perm os.FileMode
}

// DiskConfig is what a Disk needs.
type DiskConfig struct {
	// Root is the mount point. It is created if it does not exist, which covers
	// the docker-compose bind mount; a PVC arrives already there.
	Root string
	// FileMode defaults to 0640. The volume holds agent output, which is
	// customer material, and nothing outside this process reads it.
	FileMode os.FileMode
}

// NewDisk opens the volume and proves it is writable.
//
// The write probe is not ceremony. A PVC that failed to bind, or mounted
// read-only because the access mode did not match the storage class, is
// otherwise discovered by the first run that finishes — an hour and one model
// bill after the mistake was made, and reported as a lost result rather than as
// a broken mount.
func NewDisk(cfg DiskConfig) (*Disk, error) {
	if strings.TrimSpace(cfg.Root) == "" {
		return nil, errors.New("artifacts: the artifact volume needs a root path")
	}
	perm := cfg.FileMode
	if perm == 0 {
		perm = 0o640
	}
	root, err := filepath.Abs(cfg.Root)
	if err != nil {
		return nil, fmt.Errorf("artifacts: resolve %s: %w", cfg.Root, err)
	}
	if err := os.MkdirAll(root, perm|0o111); err != nil {
		return nil, fmt.Errorf("artifacts: create %s: %w", root, err)
	}

	probe := filepath.Join(root, ".haliphron-writable")
	if err := os.WriteFile(probe, []byte("ok"), perm); err != nil {
		return nil, fmt.Errorf("artifacts: %s is not writable; "+
			"check that the artifact volume is bound and its access mode allows this replica to write: %w",
			root, err)
	}
	_ = os.Remove(probe)

	return &Disk{root: root, perm: perm}, nil
}

// Scheme is file, which is what a result_ref written by this store says.
func (d *Disk) Scheme() string { return runv1.SchemeFile }

// Mode is relay.
func (d *Disk) Mode() runv1.ArtifactMode { return runv1.ArtifactModeRelay }

// Bucket is empty: there is no bucket, and a placeholder here would end up in a
// result_ref that looks like an object store's and is not.
func (d *Disk) Bucket() string { return "" }

// Endpoint is the root path, for log lines and the operator endpoint.
func (d *Disk) Endpoint() string { return d.root }

// Root is the mount point, for the reaper.
func (d *Disk) Root() string { return d.root }

// Put writes an object.
func (d *Disk) Put(ctx context.Context, key string, body []byte, contentType string) error {
	_, err := d.PutStream(ctx, key, strings.NewReader(string(body)), contentType)
	return err
}

// PutStream writes without buffering, through a temporary file renamed into
// place.
//
// The rename is what makes a half-written object impossible to read. Relay mode
// can be interrupted mid-transfer — a controller restarting, a connection
// dropping — and an incomplete result.md sitting under the right key is worse
// than no result.md at all: the CompletedWithoutResult recovery path would read
// it and believe it. A rename within one filesystem is atomic, so a reader sees
// either the previous object or the whole new one.
func (d *Disk) PutStream(_ context.Context, key string, body io.Reader, contentType string) (runv1.ObjectRef, error) {
	path, err := d.path(key)
	if err != nil {
		return runv1.ObjectRef{}, err
	}
	if err := os.MkdirAll(filepath.Dir(path), d.perm|0o111); err != nil {
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: create the directory for %s: %w", key, err)
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), ".partial-*")
	if err != nil {
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: open a temporary file for %s: %w", key, err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	sum := sha256.New()
	written, err := io.Copy(io.MultiWriter(tmp, sum), body)
	if err != nil {
		_ = tmp.Close()
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: write %s: %w", key, err)
	}
	// Synced before the rename. Without it the rename can land in the journal
	// ahead of the data, and a node that loses power leaves a zero-length
	// object under a key the database says holds a result.
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: sync %s: %w", key, err)
	}
	if err := tmp.Close(); err != nil {
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: close %s: %w", key, err)
	}
	if err := os.Chmod(tmpName, d.perm); err != nil {
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: chmod %s: %w", key, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return runv1.ObjectRef{}, fmt.Errorf("artifacts: publish %s: %w", key, err)
	}

	return runv1.ObjectRef{
		Key:         key,
		SizeBytes:   written,
		SHA256:      hex.EncodeToString(sum.(hash.Hash).Sum(nil)),
		ContentType: contentType,
		Uploaded:    true,
	}, nil
}

// Get reads an object whole.
func (d *Disk) Get(ctx context.Context, key string) ([]byte, error) {
	f, err := d.Open(ctx, key)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	body, err := io.ReadAll(f)
	if err != nil {
		return nil, fmt.Errorf("artifacts: read %s: %w", key, err)
	}
	return body, nil
}

// Open streams an object out.
func (d *Disk) Open(_ context.Context, key string) (io.ReadCloser, error) {
	path, err := d.path(key)
	if err != nil {
		return nil, err
	}
	f, err := os.Open(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, fmt.Errorf("artifacts: open %s: %w", key, ErrNotFound)
	}
	if err != nil {
		return nil, fmt.Errorf("artifacts: open %s: %w", key, err)
	}
	return f, nil
}

// List enumerates a prefix, sorted by key so that a paged reader sees a stable
// order.
func (d *Disk) List(_ context.Context, prefix string) ([]Object, error) {
	// The walk starts at the deepest directory the prefix names, so listing one
	// run's logs does not read every run on the volume. A prefix that ends
	// mid-name — "logs/chunks/1" — walks its parent and filters.
	start, err := d.path(strings.TrimSuffix(prefix, "/"))
	if err != nil {
		return nil, err
	}
	if info, statErr := os.Stat(start); statErr != nil || !info.IsDir() {
		start = filepath.Dir(start)
	}

	var out []Object
	err = filepath.WalkDir(start, func(path string, entry fs.DirEntry, err error) error {
		switch {
		case errors.Is(err, fs.ErrNotExist):
			// An empty prefix is an empty listing, not a failure: a run that
			// has produced nothing yet is the normal state of a running run.
			return filepath.SkipAll
		case err != nil:
			return err
		case entry.IsDir():
			return nil
		}
		key, relErr := filepath.Rel(d.root, path)
		if relErr != nil {
			return nil
		}
		key = filepath.ToSlash(key)
		if !strings.HasPrefix(key, prefix) || strings.HasPrefix(entry.Name(), ".partial-") {
			return nil
		}
		info, infoErr := entry.Info()
		if infoErr != nil {
			return nil
		}
		out = append(out, Object{
			Key: key, SizeBytes: info.Size(), LastModified: info.ModTime(),
		})
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("artifacts: list %s: %w", prefix, err)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key < out[j].Key })
	return out, nil
}

// Delete removes one object, and any directories it leaves empty.
//
// The directory sweep matters more here than it would in a bucket: an object
// store has no directories to leak, while a volume that keeps one empty
// runs/{id}/logs/chunks/ per run accumulates inodes until the filesystem runs
// out of them long before it runs out of bytes.
func (d *Disk) Delete(_ context.Context, key string) error {
	path, err := d.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("artifacts: delete %s: %w", key, err)
	}
	for dir := filepath.Dir(path); dir != d.root && strings.HasPrefix(dir, d.root); dir = filepath.Dir(dir) {
		if err := os.Remove(dir); err != nil {
			// Not empty, or gone already. Either way there is nothing to do and
			// nothing worth reporting.
			return nil
		}
	}
	return nil
}

// PresignGet, PresignPut and PresignPost are unsupported.
//
// A disk store in object-store mode is a misconfiguration, refused at startup.
// These exist so that the refusal has one shape wherever it is reached, rather
// than an empty bundle a pod discovers an hour into its work.
func (d *Disk) PresignGet(string, time.Duration) (clusterv1.PresignedURL, error) {
	return clusterv1.PresignedURL{}, ErrPresignUnsupported
}

func (d *Disk) PresignPut(string, time.Duration) (clusterv1.PresignedURL, error) {
	return clusterv1.PresignedURL{}, ErrPresignUnsupported
}

func (d *Disk) PresignPost(string, time.Duration, int64) (clusterv1.PresignedPostPolicy, error) {
	return clusterv1.PresignedPostPolicy{}, ErrPresignUnsupported
}

// path resolves a key under the root and refuses anything that is not already a
// clean relative key.
//
// The check is not theatre. The keys reaching this store come from a pod, by
// way of a controller and the Cluster API; both of those stamp the run prefix
// themselves, and this is the third place the same rule is enforced, because a
// traversal here writes into the control plane's filesystem rather than into
// one run's prefix.
//
// It refuses rather than sanitises, and the difference matters. Rooting the key
// and calling filepath.Clean — the obvious implementation — turns "../x" into
// "/x" and writes it at the top of the volume: nothing escapes, and the object
// has silently left the run's prefix, where nobody will look for it and the
// next run's identically malformed key will overwrite it. A key that is not
// what it should be is a defect upstream, and the useful answer is to say so.
func (d *Disk) path(key string) (string, error) {
	switch {
	case key == "":
		return "", fmt.Errorf("artifacts: the empty key names no object")
	case strings.HasPrefix(key, "/"):
		return "", fmt.Errorf("artifacts: key %q is absolute; keys are relative to the volume", key)
	case key != path.Clean(key):
		return "", fmt.Errorf("artifacts: key %q is not normalised", key)
	case key == ".." || strings.HasPrefix(key, "../") || strings.Contains(key, "/../"):
		return "", fmt.Errorf("artifacts: key %q escapes the artifact volume", key)
	}

	full := filepath.Join(d.root, filepath.FromSlash(key))
	// Belt and braces: after all of the above this cannot fire, and it is the
	// one check whose failure would be silent rather than noisy.
	if full != d.root && !strings.HasPrefix(full, d.root+string(os.PathSeparator)) {
		return "", fmt.Errorf("artifacts: key %q escapes the artifact volume", key)
	}
	return full, nil
}
